### ISSUE TITLE
Example test from README failing due to TypeError

### ISSUE THREAD

**Issue by mahula** [testproject-io/robot-library#13]
The example test in the README file is failing due to a TypeError in __init__()

```
Initializing TestProject Library for Robot v0.65.1...
Set Session :: Set the keyword which should run on Failure to 'None'. | FAIL |
Parent suite setup failed:
TypeError: __init__() got an unexpected keyword argument 'projectname'
------------------------------------------------------------------------------
```

Even when using `Init Testproject Driver` in the Keyword `Init Session` without any arguments.

**Comment by Rantzur1992** [comment]
Thanks for the update, indeed a change in the python sdk is causing this issue.

It will be fixed asap.

**Comment by Rantzur1992** [comment]
@mahula There seems to be an issue in the Evaluate keyword on the latest robot framework build, so it needs to be removed for now.

Besides that, this fix will solve the parameter name issue: #14

**Comment by Rantzur1992** [comment]
Hello @mahula 
Please download version 0.65.2, it includes the fix.

**Comment by mahula** [comment]
Thanx @Rantzur1992, it works fine now.

**Comment by mahula** [comment]
The problem occurs again.
This time the unexpected keyword is **project_name** instead of **projectname**.

```
Initializing TestProject Library for Robot v0.65.2...
Set Session                                                           | FAIL |
Parent suite setup failed:
TypeError: __init__() got an unexpected keyword argument 'project_name'
```

```
Example Test                                                          | FAIL |
Suite setup failed:
TypeError: __init__() got an unexpected keyword argument 'project_name'
```

TestProject Library for Robot v**0.65.2**
Robot Framework **4.0.3** (Python **3.8.5** on linux)
